-- Existing site content, seeded once. Later edits and deletions are preserved.
INSERT INTO site_content(kind,id,data,created_at) VALUES ('news','news-1','{"id":"news-1","category":"Цифровая медицина","title":"В Казахстане формируется единая цифровая архитектура здравоохранения","description":"ЕГМИС объединит медицинские сервисы в экосистему E-Densaulyq. К декабрю 2026 года система должна стать основной платформой управления отраслью.","source":"Министерство здравоохранения РК","url":"https://www.gov.kz/memleket/entities/dsm/press/news/details/1159176?lang=ru","translationKey":"news-1"}'::jsonb,NOW()-INTERVAL '0 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('news','news-2','{"id":"news-2","category":"ОСМС","title":"Цифровизация здравоохранения и устойчивость системы ОСМС","description":"Около 17 млн казахстанцев охвачены системой ОСМС. Цифровые инструменты усиливают прозрачность, контроль качества и доступность медицинской помощи.","source":"Министерство здравоохранения РК","url":"https://www.gov.kz/memleket/entities/dsm/press/news/details/1128093?lang=ru","translationKey":"news-2"}'::jsonb,NOW()-INTERVAL '1 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('news','news-3','{"id":"news-3","category":"Здравоохранение","title":"Казахстан вошёл в топ стран по снижению смертности от хронических заболеваний","description":"Минздрав представил ключевые показатели отрасли: развитие онлайн-медицины, снижение материнской и младенческой смертности и укрепление кадрового потенциала.","source":"Министерство здравоохранения РК","url":"https://www.gov.kz/memleket/entities/dsm/press/news/details/1129298?lang=ru","translationKey":"news-3"}'::jsonb,NOW()-INTERVAL '2 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('reviews','2gis-1','{"id":"2gis-1","name":"Евгений Ким","date":"9 июля 2026","rating":5,"message":"Хорошая клиника, особенно врач-нефролог Мукашова Айжан Еркінқызы: в свой выходной приняла и выписала направление.","source":"2ГИС"}'::jsonb,NOW()-INTERVAL '0 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('reviews','2gis-2','{"id":"2gis-2","name":"Асель Сундетова","date":"30 июня 2026","rating":5,"message":"Керемет сапа. Жақсы персонал.","source":"2ГИС"}'::jsonb,NOW()-INTERVAL '1 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('reviews','2gis-3','{"id":"2gis-3","name":"Alima Kulzhabayeva","date":"29 июня 2026","rating":5,"message":"Проходила УЗИ сердца. Хорошие, вежливые врачи. Спасибо им. Мне понравился медцентр.","source":"2ГИС"}'::jsonb,NOW()-INTERVAL '2 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('reviews','2gis-4','{"id":"2gis-4","name":"Гулбахар Сейтимбетова","date":"25 июня 2026","rating":5,"message":"Была в медцентре «Нарамед Green City». Пульмонолог Ыдырыс Ұлшай Батырханқызы очень образованная, всё проверила и объяснила. Спасибо большое ей.","source":"2ГИС"}'::jsonb,NOW()-INTERVAL '3 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('reviews','2gis-5','{"id":"2gis-5","name":"Banu Arslanova","date":"25 июня 2026","rating":5,"message":"Хорошая клиника, приняли вовремя, всё чётко объяснили.","source":"2ГИС"}'::jsonb,NOW()-INTERVAL '4 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('reviews','2gis-6','{"id":"2gis-6","name":"Barsha Tsoy","date":"22 июня 2026","rating":5,"message":"Хорошая клиника, эндокринолог Эльмира Хамитовна — топ. Анализы берут очень хорошо, без стресса и безболезненно, даже у ребёнка. Всегда чисто.","source":"2ГИС"}'::jsonb,NOW()-INTERVAL '5 microseconds') ON CONFLICT DO NOTHING;
INSERT INTO site_content(kind,id,data,created_at) VALUES ('vacancies','vacancy-1','{"id":"vacancy-1","title":"Врач общей практики","department":"Амбулаторное отделение","employment":"Полная занятость","description":"Ищем внимательного врача для амбулаторного приёма пациентов.","requirements":"Высшее медицинское образование, действующий сертификат специалиста.","contact":"+7 707 534 0824","published":true,"translationKey":"vacancy-1"}'::jsonb,NOW()-INTERVAL '0 microseconds') ON CONFLICT DO NOTHING;
